[package]
name = "rust_levelup"
version = "0.1.0"
authors = ["James Rocker <james.rocker@simplybusiness.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "myswankynewlib"
path = "src/lib.rs"

[dependencies]
